// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZIMzerdXMUW5RxT6WcCR00Rr0ECqzC7U',
    appId: '1:161578457175:web:edaa8ff194e3cbc6192b12',
    messagingSenderId: '161578457175',
    projectId: 'tripmanagement-5ec73',
    authDomain: 'tripmanagement-5ec73.firebaseapp.com',
    storageBucket: 'tripmanagement-5ec73.firebasestorage.app',
    measurementId: 'G-0W8T665M0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg6UIpi8SmyUG_EBFew4Nk8rONHw1KxIk',
    appId: '1:161578457175:android:b798251cc2bd5161192b12',
    messagingSenderId: '161578457175',
    projectId: 'tripmanagement-5ec73',
    storageBucket: 'tripmanagement-5ec73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs--0vCby5hVTB0M5DZ6N1Ycmwa5AFVUw',
    appId: '1:161578457175:ios:dde2b897dd9cf153192b12',
    messagingSenderId: '161578457175',
    projectId: 'tripmanagement-5ec73',
    storageBucket: 'tripmanagement-5ec73.firebasestorage.app',
    iosBundleId: 'com.sang89.tripManagement',
  );
}
